services:
  - type: web
    name: telegram-time-updater
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python TimeUpdaterBot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
